spring.application.name=gateway
server.port=8080
eureka.client.region=default
eureka.client.registryFetchIntervalSeconds=5

management.security.sessions=always
spring.redis.host=localhost
spring.redis.port=6379