spring.application.name=gateway
server.port=8080
eureka.client.region=default
eureka.client.registryFetchIntervalSeconds=5
eureka.client.serviceUrl.defaultZone=http://discUser:discPassword@localhost:8082/eureka/

management.security.sessions=always
spring.redis.host=localhost
spring.redis.port=6379